language: python
python:
  - "3.6.2"
install:
  - git clone https://github.com/rbenv/rbenv.git ~/.rbenv
  - echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
  - echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
  - source ~/.bash_profile
  - git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
  - rbenv install 2.4.1
  - rbenv global 2.4.1
  - gem install msgpack-rpc
  - pip install msgpack-rpc-python
script: python -m unittest discover -v
cache:
  bundler: true
  pip: true
